### ISSUE TITLE
Services Médicaux - New Text + image

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#13]
Hello @Yago 
- [x] add the new text from contentful
- [x] add the new image. Please find the link below.

afp://hal9000._afpovertcp._tcp.local/Projects/677_refonte_hopitalrivierachablais_ch/graphic/Img-definitive-website/Images-lastselection/_EXP/HRC_CoverServicester.jpg

**Comment by Yago** [comment]
Cover are Contentful stuff and you can do it 😉
