### ISSUE TITLE
teaser of the service "Physiotherapie & ergothérapie" - link broken

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#14]
- [x] the teaser have not the right link. Please add the right one.

Explanation : 
- http://hrc.alwaysdata.net/physiotherapie-et-ergotherapie => 404 but it is the good URL
- http://hrc.alwaysdata.net/physiotherapie/ => this one works but is not the good one
- the titel of the service has been updated

**Comment by Yago** [comment]
“the title of the service has been updated” -> that's the reason why, changing title may broke the site
