### ISSUE TITLE
Have an interactive map

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#17]
Is it possible to add link in an image ? The client would like to be able to clic on the hospital and be redirected to the detail page of that chosen hospital.

![screen shot 2016-06-08 at 11 28 32](https://cloud.githubusercontent.com/assets/12033929/15889624/26103536-2d6c-11e6-9131-74ea1d6590fc.png)

**Comment by Yago** [comment]
It is possible, but not for the first released version.
