### ISSUE TITLE
Home page - Phone of Hospital 

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#2]
Basecamp : https://basecamp.com/1791151/projects/11629353/todos/254179551

We need to make sure people understand the difference between the emergency and the secretary number. 

=> What would you suggest on basis of Noémie's proposal ?

**Comment by ludovicrenevey** [comment]
@Yago : what do you think of the example of Noémie ? I would add the word "urgence" in the same color.

**Comment by Yago** [comment]
I have no objections, I just need an emergency phone number for each hospital in Contentfull

**Comment by Yago** [comment]
I have no objections, I just need an emergency phone number for each hospital in Contentfull

**Comment by Yago** [comment]
@ludovicrenevey Normally it should work, you just have to fill the emergency hospital fiel in Contentful 😉
