### ISSUE TITLE
Cancérologie is not accessible anymore

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#26]
We changed the tile of the page and this URL : 
http://hrc.alwaysdata.net/service-interdisciplinaire-de-cancerologie

does not work anymore.

Not Found
The requested URL /service-interdisciplinaire-de-cancerologie was not found on this server.

**Comment by Yago** [comment]
@ludovicrenevey @nsz @gido  ⚠️  Anytimes you change a title, this will break the site

**Comment by nsz** [comment]
@Yago du coup, avant de changer, on te prévient ? Ou qu'est-ce tu aimerais comme procédure ?

**Comment by Yago** [comment]
Ouai, juste avant de changer je fait le changement et je vous donne le go 😉
