### ISSUE TITLE
Add caption to picture

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#29]
How can we do this ?
How long does it take ?

<img width="1159" alt="screen shot 2016-06-13 at 17 01 47" src="https://cloud.githubusercontent.com/assets/12033929/16012177/9a27c252-3188-11e6-8362-1f43ffc794dd.png">

**Comment by Yago** [comment]
@ludovicrenevey Yes we can 🇺🇸  But you need first add a “description” to every Contentful media and I will do it in 1 and a half hour.

**Comment by Yago** [comment]
@ludovicrenevey Status here ?
