### ISSUE TITLE
HTML/CSS - Consultation Teaser + full

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#31]
**Explanation**
- Bloc on the homepage
- Detail's page (regarding this page, @nsz should be involved, @Yago !!)

**Full :** 
![screen shot 2016-06-14 at 17 21 36](https://cloud.githubusercontent.com/assets/12033929/16048462/79dc39de-3254-11e6-9113-4e4c26a5cd6b.png)

**Teaser :** 
![screen shot 2016-06-14 at 17 20 07](https://cloud.githubusercontent.com/assets/12033929/16048441/5f6ebdd8-3254-11e6-988a-a1b6f4e0ac61.png)

**Design home**
![screen shot 2016-06-14 at 17 33 36](https://cloud.githubusercontent.com/assets/12033929/16048975/51c6b36e-3256-11e6-86b2-d9d4ef787823.png)

**Comment by ludovicrenevey** [comment]
I had a point to this issue : 

> How should we manage the consultation in the page of a service. Should we check it with the client ?

In the static version, we only have the list of all doctors/nurses.

<img width="435" alt="screen shot 2016-06-14 at 19 05 09" src="https://cloud.githubusercontent.com/assets/12033929/16052149/2ad7b96c-3263-11e6-893a-5aeb7f3f6008.png">

**Comment by Yago** [comment]
@ludovicrenevey We need to have a well thought design of those **consultation component**, hierarchy in mind. It have also to be validated by the client and FHVI. Frontend design is not the right way in this case.

**Comment by ludovicrenevey** [comment]
@Yago : I should do separated issues for those component : 
- Bloc on the service page
- Teaser on home page (research)
- Search result of the detail page 

What do you think ? I think that you have a question for all the component but not the one for the homepage ?

**Comment by nsz** [comment]
@ludovicrenevey (cc. @Yago @zufrieden )
Les consultations sont un point assez compliqué et sur lequel la FHVI nous a déjà mis plein de warning. Je pense que ce serait bien de refaire valider le fonctionnement (avec Marc), de le faire designer par Zhiqi et ensuite Yann pourra le coder.

**Comment by Yago** [comment]
done (http://hrc.alwaysdata.net/styleguide/organisms/#organism1)
