### ISSUE TITLE
HTML/CSS - Emploi Teaser + full

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#32]
**Explanation**
- Bloc on the homepage
- Full page with same link but with an introduction text.

*_Question for @nsz *_
- Comment avions-nous pensez ceci ? Linkedin ?
- Si on clique sur la home (sur le lien d'un poste), on arrive où ?

**Full**
![screen shot 2016-06-14 at 17 28 34](https://cloud.githubusercontent.com/assets/12033929/16048931/27cc5564-3256-11e6-973b-b8eda9a96dea.png)

**Teaser**
![screen shot 2016-06-14 at 17 27 50](https://cloud.githubusercontent.com/assets/12033929/16048930/27cc4272-3256-11e6-9cbd-992134d8a487.png)

**Design home**
![screen shot 2016-06-14 at 17 33 26](https://cloud.githubusercontent.com/assets/12033929/16048939/2f807e70-3256-11e6-8858-2759d8d1cb93.png)

**Comment by nsz** [comment]
@ludovicrenevey 
Comment avions-nous pensez ceci ? Linkedin ?
--> oui, ils ont mis les annonces sur linkedin, à discuter avec eux mais je pense que c'est un bon système.

Si on clique sur la home, on arrive où ?
--> pas compris

**Comment by ludovicrenevey** [comment]
@nsz : J'ai updaté le post initial : 

> Si on clique sur la home (sur le lien d'un poste), on arrive où ?
- Linkedin
- Page emploi

**Comment by nsz** [comment]
@ludovicrenevey 
- Si on clique sur un poste --> linkedin
- Si on clique sur voir toutes nos offres d'emploi --> page emploi

**Comment by Yago** [comment]
The new design looks more like :

![capture d ecran 2016-06-30 a 10 38 14](https://cloud.githubusercontent.com/assets/2025924/16483288/139deab6-3eb4-11e6-88b1-2d02f5f93015.png)
