### ISSUE TITLE
HTML/CSS - News Teaser + Full

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#33]
**Explanation**
- New element in the design
- No Wireframes, @nsz do we need it for @Yago ?
- No place in the sitemap, @nsz ?

**Design home**
![screen shot 2016-06-14 at 17 33 32](https://cloud.githubusercontent.com/assets/12033929/16049069/ae2ea9ea-3256-11e6-9336-9f307d7607ae.png)

**Comment by nsz** [comment]
@ludovicrenevey 
Tu parles bien des actualités ?
A la base, ils ne voulaient pas en faire, voilà pourquoi elles ne sont pas prévues dans le sitemap.
Je ne pense pas que ça a vraiment besoin d'une wireframe mais redites moi @Yago @ludovicrenevey

**Comment by ludovicrenevey** [comment]
C'est juste @nsz. Faisons ainsi. Si Yann en a besoin, il te ping directement. Ok pour toi @Yago ?

**Comment by Yago** [comment]
Yep, postponed to final version

**Comment by Yago** [comment]
Maybe a link will be a good idea
