### ISSUE TITLE
HTML/CSS - Site de demain

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#34]
**Explanation**
- Special webpage for Rennaz
- Design of Zhiqi : https://invis.io/6A6WS0PDW

**Questions**
- The wireframes had a gallery for this page.
- Should we modify this page in order to have a real gallery after the text or should we left it on the right side ?
- The 2nd second is linked to this one. What do we do with the text ? Should the text have a with of 100%, should we center it or keep it that way ? To check with Zhiqi !!

**Comment by Yago** [comment]
⚠️  Because of Contentful, we can't do better than having 2 text columns as discussed with Zhiqi. I remind you, it's a **MVP temporary website**, not the nice fancy final version ⚠️ 
@ludovicrenevey @gido

**Comment by ludovicrenevey** [comment]
Please keep this issue opened :) So that we discuss of it for the final version of the website.

I will not do others issues for that :)

**Comment by Yago** [comment]
Ho sorry, I wont

**Comment by Yago** [comment]
Preview in [http://hrc.alwaysdata.net/rennaz/](http://hrc.alwaysdata.net/rennaz/), but **huge warning here** : it's a page, not a static website dynamic content page ! Only for preview purpose 😉
