### ISSUE TITLE
HTML/CSS - Mode d'emploi Full on mobile

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#35]
**Explanation**
- On mobile, could we think of an user friendlier interface ?
- Please look at the wireframe

<img width="330" alt="screen shot 2016-06-14 at 19 08 36" src="https://cloud.githubusercontent.com/assets/12033929/16052339/1428d1e6-3264-11e6-9b63-27d6d190cec8.png">

**Comment by Yago** [comment]
@ludovicrenevey @gido ⚠️ This tocnav JS creation is **temporary** because of Contentful. This should not be implemented this way in the final website version !!!  ⚠️

**Comment by gido** [comment]
ok. You can flag your code with `// @TODO more infos here` or `@FIXME`
