### ISSUE TITLE
HTML/CSS - Presse page (full)

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#36]
**Explanation**
- Page in the second nav
- Documents are PDF

<img width="939" alt="screen shot 2016-06-14 at 19 16 34" src="https://cloud.githubusercontent.com/assets/12033929/16052463/b0004bf8-3264-11e6-877c-a2bd7b93ba53.png">

**Comment by Yago** [comment]
@ludovicrenevey Say that it's only for styleguide purpose, so postponed for later version
