### ISSUE TITLE
Add new img - page contact

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#37]
[Cover-HRC-pagecontact.zip](https://github.com/antistatique/hrc/files/331862/Cover-HRC-pagecontact.zip)

![cover-hrc-pagecontact](https://cloud.githubusercontent.com/assets/12033929/16340297/a5cbe406-3a27-11e6-8ca1-a42d8dc9e7a7.png)

**Comment by Yago** [comment]
I will do it, but it's Contentful stuff 😅
