### ISSUE TITLE
Possibility of download PDF

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#38]
**Explanation**
The client asks if there is a possibility to add downloadable PDF ?

**Solutions ?**
- This could be a link with target="_blank"
- The FHVi can host them anywhere they want
- Or something else ?

**Comment by ludovicrenevey** [comment]
No specific page for now. The client only asked me if this is possible for the static website. I think he would need it for the services.

**Comment by Yago** [comment]
Only if it's vital for the MVP, you can add a new media field on the targeted Contentful's content type and edit the right entry. After that, I will put the link where it's needed :wink:
