### ISSUE TITLE
Sticky second menu

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#44]
@Yago : 
- Service page
- Séjour à l'hôpital

<img width="1147" alt="screen shot 2016-09-07 at 11 41 55" src="https://cloud.githubusercontent.com/assets/12033929/18307313/2a30a2a6-74f0-11e6-8ea9-73b504d7cd70.png">

**Comment by Yago** [comment]
Can be previewed [here](http://antistatique.github.io/hrc/tocnav-page/)
