### ISSUE TITLE
Help for FHVi

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#45]
- [x] Ajouter des sous-menus dans le menu principal. Should we do something ?
- [x] Composant consultation, il faut passer le titre du H3 à H4. 
- [x] Vidéo, il faut fournir le code responsive à la FHVi.
- [x] Exemple de page média 
- [x] Exemple de page page fournisseur\* 
- [x] Exemple de page détail d’une actualité
- [x] Exemple de page détail emploi

*Content : 
https://basecamp.com/1791151/projects/11629353/messages/60922981#comment_454738705

**Comment by ludovicrenevey** [comment]
@Yago It is all right for me but I have a few questions : 
- If they want a gallery such as the one we did for HOS. What would that cost?
- Please rename the Article detail page => emploi
- Please add a new page for the Article detail page with tag and date.

**Comment by Yago** [comment]
1. You mean a fancy ratio-grid for thumbnails ? around 6h
2. ?
3. Rather that, I will add the missing tag and date 😉
