### ISSUE TITLE
Services Médicaux - New Text

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/hrc#8]
New Body entry for this page !

![screen shot 2016-06-03 at 14 30 52](https://cloud.githubusercontent.com/assets/12033929/15778658/d531a294-2997-11e6-8334-6ec1069a343f.png)

**Comment by ludovicrenevey** [comment]
@Yago : Can you add it ?

**Comment by Yago** [comment]
I don't understand the request

**Comment by ludovicrenevey** [comment]
@Yago We should have a introduction on this page. Now we only have the titel and the teasers. 

<img width="1268" alt="screen shot 2016-06-06 at 16 38 23" src="https://cloud.githubusercontent.com/assets/12033929/15825724/2df0f7b2-2c05-11e6-8936-9b4b4f6bf3e1.png">

**Comment by Yago** [comment]
haaa ok
